/* ═══════════════════════════════════════════════════════════════
   StudyVerse — Professional PDF Generator Utility
   Produces clean, branded A4 PDFs with:
     • Platform logo + header on every page
     • Proper fonts (Helvetica family)
     • Consistent spacing, margins, and colour palette
     • Page numbers in the footer
     • Structured tables and result cards
   ═══════════════════════════════════════════════════════════════ */

// Brand colours (matching the app palette)
const BRAND = {
  primary:    [108, 99, 255],   // #6C63FF
  primaryDk:  [88,  79, 215],   // darker accent
  secondary:  [56, 178, 172],   // #38B2AC
  dark:       [61,  72,  82],   // #3D4852
  muted:      [107, 114, 128],  // #6B7280
  light:      [224, 229, 236],  // #E0E5EC
  white:      [255, 255, 255],
  tableHead:  [108, 99, 255],
  tableStripe:[243, 244, 246],  // #F3F4F6
  success:    [16, 185, 129],   // green
  warning:    [245, 158, 11],   // amber
  danger:     [239, 68, 68],    // red
};

// Layout constants (mm)
const MARGIN = { top: 38, left: 20, right: 20, bottom: 25 };
const PAGE_W = 210;  // A4
const CONTENT_W = PAGE_W - MARGIN.left - MARGIN.right;

// ─── Logo loader (caches the base64 image) ────────────────────
let _logoCache = null;

function loadLogo() {
  if (_logoCache) return Promise.resolve(_logoCache);
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      _logoCache = canvas.toDataURL('image/jpeg', 0.92);
      resolve(_logoCache);
    };
    img.onerror = () => resolve(null);
    img.src = '/weblogo.jpeg';
  });
}

// ─── Shared helpers ───────────────────────────────────────────
function rgb(arr) { return arr; }

function addPageHeader(doc, logoData, title) {
  const y = 12;
  // Logo
  if (logoData) {
    doc.addImage(logoData, 'JPEG', MARGIN.left, y - 4, 14, 14);
  }
  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...rgb(BRAND.primary));
  doc.text('StudyVerse', MARGIN.left + 18, y + 6);

  // Document title (right-aligned)
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...rgb(BRAND.muted));
  doc.text(title, PAGE_W - MARGIN.right, y + 6, { align: 'right' });

  // Divider line
  doc.setDrawColor(...rgb(BRAND.primary));
  doc.setLineWidth(0.6);
  doc.line(MARGIN.left, y + 12, PAGE_W - MARGIN.right, y + 12);
}

function addPageFooter(doc, pageNum, totalPages) {
  const y = 290;
  // Divider
  doc.setDrawColor(...rgb(BRAND.light));
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y - 4, PAGE_W - MARGIN.right, y - 4);

  // Left — branding
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(...rgb(BRAND.muted));
  doc.text('Generated by StudyVerse AI Platform', MARGIN.left, y);

  // Centre — date
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
  doc.text(dateStr, PAGE_W / 2, y, { align: 'center' });

  // Right — page number
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN.right, y, { align: 'right' });
}

function ensureNewPage(doc, y, neededSpace, logoData, title) {
  if (y + neededSpace > 270) {
    doc.addPage();
    addPageHeader(doc, logoData, title);
    return MARGIN.top;
  }
  return y;
}

function drawRoundedRect(doc, x, y, w, h, r, fillColor) {
  doc.setFillColor(...fillColor);
  doc.roundedRect(x, y, w, h, r, r, 'F');
}

// ─── Wrap long text into multiple lines ───────────────────────
function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(text || '', maxWidth);
}


// ═══════════════════════════════════════════════════════════════
//  TIMETABLE PDF
// ═══════════════════════════════════════════════════════════════
export async function generateTimetablePDF(timetableData, preferences = {}) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p', 'mm', 'a4');
  const logoData = await loadLogo();
  const title = 'Daily Timetable';

  // ── Page 1: Title page ──────────────────────────────────────
  addPageHeader(doc, logoData, title);
  let y = MARGIN.top + 4;

  // Big title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Your AI-Generated Timetable', MARGIN.left, y);
  y += 10;

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...rgb(BRAND.muted));
  const today = new Date().toLocaleDateString('en-IN', {
    weekday: 'long', day: '2-digit', month: 'long', year: 'numeric',
  });
  doc.text(`Personalised schedule for ${today}`, MARGIN.left, y);
  y += 6;

  // Preference summary chips
  if (preferences && Object.keys(preferences).length > 0) {
    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...rgb(BRAND.dark));
    doc.text('Preferences', MARGIN.left, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...rgb(BRAND.muted));

    const prefEntries = Object.entries(preferences).filter(([, v]) => v);
    let chipX = MARGIN.left;
    for (const [key, value] of prefEntries) {
      const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
      const chipText = `${label}: ${value}`;
      const chipW = doc.getTextWidth(chipText) + 8;

      if (chipX + chipW > PAGE_W - MARGIN.right) {
        chipX = MARGIN.left;
        y += 8;
      }

      drawRoundedRect(doc, chipX, y - 4, chipW, 7, 2, BRAND.tableStripe);
      doc.text(chipText, chipX + 4, y);
      chipX += chipW + 4;
    }
    y += 12;
  }

  // ── Separator ───────────────────────────────────────────────
  doc.setDrawColor(...rgb(BRAND.light));
  doc.setLineWidth(0.4);
  doc.line(MARGIN.left, y, PAGE_W - MARGIN.right, y);
  y += 8;

  // ── Table header ────────────────────────────────────────────
  const colWidths = { time: 42, subject: 80, type: CONTENT_W - 42 - 80 };
  const cols = [
    { label: 'TIME', width: colWidths.time },
    { label: 'ACTIVITY', width: colWidths.subject },
    { label: 'TYPE', width: colWidths.type },
  ];

  // Header row background
  drawRoundedRect(doc, MARGIN.left, y - 1, CONTENT_W, 10, 2, BRAND.primary);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...rgb(BRAND.white));

  let colX = MARGIN.left + 4;
  for (const col of cols) {
    doc.text(col.label, colX, y + 5);
    colX += col.width;
  }
  y += 12;

  // ── Table rows ──────────────────────────────────────────────
  const slots = timetableData?.daily || [];
  doc.setFontSize(10);

  for (let i = 0; i < slots.length; i++) {
    y = ensureNewPage(doc, y, 12, logoData, title);

    const slot = slots[i];
    const isEven = i % 2 === 0;

    // Stripe background
    if (isEven) {
      drawRoundedRect(doc, MARGIN.left, y - 4, CONTENT_W, 10, 1.5, BRAND.tableStripe);
    }

    colX = MARGIN.left + 4;

    // Time column
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...rgb(BRAND.dark));
    doc.text(slot.time || '', colX, y + 1);
    colX += colWidths.time;

    // Activity column
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...rgb(BRAND.dark));
    doc.text((slot.subject || '').substring(0, 45), colX, y + 1);
    colX += colWidths.subject;

    // Type badge
    const typeLabel = (slot.type || 'other').toUpperCase();
    let badgeColor = BRAND.muted;
    if (slot.type === 'study')   badgeColor = BRAND.primary;
    if (slot.type === 'college') badgeColor = BRAND.warning;
    if (slot.type === 'break')   badgeColor = BRAND.success;
    if (slot.type === 'routine') badgeColor = BRAND.secondary;

    const badgeW = doc.getTextWidth(typeLabel) + 8;
    drawRoundedRect(doc, colX, y - 3.5, badgeW, 7, 2, badgeColor);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...rgb(BRAND.white));
    doc.text(typeLabel, colX + 4, y + 1);
    doc.setFontSize(10);

    y += 11;
  }

  // ── Summary stats ───────────────────────────────────────────
  y += 6;
  y = ensureNewPage(doc, y, 30, logoData, title);

  doc.setDrawColor(...rgb(BRAND.light));
  doc.setLineWidth(0.4);
  doc.line(MARGIN.left, y, PAGE_W - MARGIN.right, y);
  y += 8;

  const studyCount = slots.filter(s => s.type === 'study').length;
  const breakCount = slots.filter(s => s.type === 'break').length;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Schedule Summary', MARGIN.left, y);
  y += 8;

  // Summary cards
  const summaryItems = [
    { label: 'Total Slots', value: `${slots.length}`, color: BRAND.dark },
    { label: 'Study Blocks', value: `${studyCount}`, color: BRAND.primary },
    { label: 'Breaks', value: `${breakCount}`, color: BRAND.success },
  ];

  const cardW = (CONTENT_W - 12) / 3;
  for (let i = 0; i < summaryItems.length; i++) {
    const item = summaryItems[i];
    const cx = MARGIN.left + i * (cardW + 6);
    drawRoundedRect(doc, cx, y, cardW, 18, 3, BRAND.tableStripe);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...item.color);
    doc.text(item.value, cx + cardW / 2, y + 9, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...rgb(BRAND.muted));
    doc.text(item.label, cx + cardW / 2, y + 15, { align: 'center' });
  }

  // ── Add footers to all pages ────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addPageFooter(doc, p, totalPages);
  }

  doc.save('StudyVerse_Timetable.pdf');
}


// ═══════════════════════════════════════════════════════════════
//  ASSESSMENT PDF
// ═══════════════════════════════════════════════════════════════
export async function generateAssessmentPDF(topic, results, totalScore, maxScore) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p', 'mm', 'a4');
  const logoData = await loadLogo();
  const title = 'Assessment Report';

  // ── Page 1: Header ──────────────────────────────────────────
  addPageHeader(doc, logoData, title);
  let y = MARGIN.top + 4;

  // Report title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Assessment Report', MARGIN.left, y);
  y += 10;

  // Topic & date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...rgb(BRAND.muted));
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  doc.text(`Topic: ${topic}`, MARGIN.left, y);
  y += 6;
  doc.text(`Date: ${dateStr}`, MARGIN.left, y);
  y += 10;

  // ── Score card ──────────────────────────────────────────────
  const scorePercent = Math.round((totalScore / maxScore) * 100);
  let scoreColor = BRAND.success;
  let scoreLabel = 'Excellent';
  if (scorePercent < 40) { scoreColor = BRAND.danger; scoreLabel = 'Needs Improvement'; }
  else if (scorePercent < 70) { scoreColor = BRAND.warning; scoreLabel = 'Good'; }
  else if (scorePercent < 90) { scoreColor = BRAND.secondary; scoreLabel = 'Very Good'; }

  // Score box background
  drawRoundedRect(doc, MARGIN.left, y, CONTENT_W, 30, 4, BRAND.tableStripe);

  // Big score number
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(32);
  doc.setTextColor(...scoreColor);
  doc.text(`${totalScore}`, MARGIN.left + 14, y + 18);

  // Denominator
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(...rgb(BRAND.muted));
  const scoreNumW = doc.getTextWidth(`${totalScore}`);
  doc.setFontSize(32);
  const bigW = doc.getTextWidth(`${totalScore}`);
  doc.setFontSize(14);
  doc.text(` / ${maxScore}`, MARGIN.left + 14 + bigW + 2, y + 18);

  // Percentage badge
  const badgeX = MARGIN.left + 80;
  drawRoundedRect(doc, badgeX, y + 8, 30, 12, 3, scoreColor);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...rgb(BRAND.white));
  doc.text(`${scorePercent}%`, badgeX + 15, y + 16, { align: 'center' });

  // Grade label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...scoreColor);
  doc.text(scoreLabel, badgeX + 38, y + 16);

  // Progress bar
  const barX = MARGIN.left + 8;
  const barY = y + 24;
  const barW = CONTENT_W - 16;
  const barH = 3;
  drawRoundedRect(doc, barX, barY, barW, barH, 1.5, [220, 220, 230]);
  drawRoundedRect(doc, barX, barY, barW * (scorePercent / 100), barH, 1.5, scoreColor);

  y += 38;

  // ── Questions section ───────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Detailed Results', MARGIN.left, y);
  y += 3;

  // Divider
  doc.setDrawColor(...rgb(BRAND.primary));
  doc.setLineWidth(0.5);
  doc.line(MARGIN.left, y, MARGIN.left + 40, y);
  y += 8;

  // ── Each question card ──────────────────────────────────────
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    const answerLines = wrapText(doc, r.answer || 'No answer provided', CONTENT_W - 20);
    const feedbackLines = wrapText(doc, r.feedback || '', CONTENT_W - 20);
    const cardHeight = 28 + (answerLines.length * 5) + (feedbackLines.length * 4.5);

    y = ensureNewPage(doc, y, cardHeight + 6, logoData, title);

    // Card background
    drawRoundedRect(doc, MARGIN.left, y, CONTENT_W, cardHeight, 3, BRAND.tableStripe);

    // Question number badge
    const qBadgeW = 10;
    drawRoundedRect(doc, MARGIN.left + 4, y + 4, qBadgeW, 7, 2, BRAND.primary);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...rgb(BRAND.white));
    doc.text(`Q${i + 1}`, MARGIN.left + 4 + qBadgeW / 2, y + 9, { align: 'center' });

    // Question text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...rgb(BRAND.dark));
    const questionLines = wrapText(doc, r.question, CONTENT_W - 30);
    doc.text(questionLines, MARGIN.left + 18, y + 9);
    let innerY = y + 9 + (questionLines.length * 5) + 2;

    // Score badge for this question
    const qScore = r.score || 0;
    let qScoreColor = BRAND.success;
    if (qScore < 4) qScoreColor = BRAND.danger;
    else if (qScore < 7) qScoreColor = BRAND.warning;

    const scoreBadgeX = PAGE_W - MARGIN.right - 24;
    drawRoundedRect(doc, scoreBadgeX, y + 3, 20, 8, 2, qScoreColor);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...rgb(BRAND.white));
    doc.text(`${qScore}/10`, scoreBadgeX + 10, y + 8.5, { align: 'center' });

    // Answer section
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...rgb(BRAND.muted));
    doc.text('YOUR ANSWER', MARGIN.left + 8, innerY);
    innerY += 4;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...rgb(BRAND.dark));
    doc.text(answerLines, MARGIN.left + 8, innerY);
    innerY += answerLines.length * 4.5 + 3;

    // Feedback section
    if (r.feedback) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...rgb(BRAND.secondary));
      doc.text('AI FEEDBACK', MARGIN.left + 8, innerY);
      innerY += 4;

      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(...rgb(BRAND.muted));
      doc.text(feedbackLines, MARGIN.left + 8, innerY);
    }

    y += cardHeight + 6;
  }

  // ── Add footers to all pages ────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addPageFooter(doc, p, totalPages);
  }

  doc.save('StudyVerse_Assessment.pdf');
}
