/* ═══════════════════════════════════════════════════════════════
   StudyVerse — Professional PDF Generator Utility
   ═══════════════════════════════════════════════════════════════ */

const BRAND = {
  primary: [108,99,255], primaryDk: [88,79,215], secondary: [56,178,172],
  dark: [61,72,82], muted: [107,114,128], light: [224,229,236],
  white: [255,255,255], tableStripe: [243,244,246],
  success: [16,185,129], warning: [245,158,11], danger: [239,68,68],
};
const MARGIN = { top: 38, left: 20, right: 20, bottom: 25 };
const PAGE_W = 210;
const CONTENT_W = PAGE_W - MARGIN.left - MARGIN.right;

let _logoCache = null;
function loadLogo() {
  if (_logoCache) return Promise.resolve(_logoCache);
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const c = document.createElement('canvas'); c.width = img.width; c.height = img.height;
      c.getContext('2d').drawImage(img, 0, 0);
      _logoCache = c.toDataURL('image/jpeg', 0.92); resolve(_logoCache);
    };
    img.onerror = () => resolve(null);
    img.src = '/weblogo.jpeg';
  });
}

function rgb(a) { return a; }
function rr(doc, x, y, w, h, r, c) { doc.setFillColor(...c); doc.roundedRect(x, y, w, h, r, r, 'F'); }
function wrap(doc, t, mw) { return doc.splitTextToSize(t || '', mw); }

function addHeader(doc, logo, title) {
  const y = 12;
  if (logo) doc.addImage(logo, 'JPEG', MARGIN.left, y - 4, 14, 14);
  doc.setFont('helvetica','bold'); doc.setFontSize(16); doc.setTextColor(...rgb(BRAND.primary));
  doc.text('StudyVerse', MARGIN.left + 18, y + 6);
  doc.setFont('helvetica','normal'); doc.setFontSize(10); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(title, PAGE_W - MARGIN.right, y + 6, { align: 'right' });
  doc.setDrawColor(...rgb(BRAND.primary)); doc.setLineWidth(0.6);
  doc.line(MARGIN.left, y + 12, PAGE_W - MARGIN.right, y + 12);
}

function addFooter(doc, p, total) {
  const y = 290;
  doc.setDrawColor(...rgb(BRAND.light)); doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y - 4, PAGE_W - MARGIN.right, y - 4);
  doc.setFont('helvetica','italic'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.muted));
  doc.text('Generated by StudyVerse AI Platform', MARGIN.left, y);
  doc.text(new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }), PAGE_W/2, y, { align:'center' });
  doc.setFont('helvetica','normal');
  doc.text(`Page ${p} of ${total}`, PAGE_W - MARGIN.right, y, { align:'right' });
}

function newPage(doc, y, need, logo, title) {
  if (y + need > 270) { doc.addPage(); addHeader(doc, logo, title); return MARGIN.top; }
  return y;
}

function finalize(doc) {
  const t = doc.internal.getNumberOfPages();
  for (let p = 1; p <= t; p++) { doc.setPage(p); addFooter(doc, p, t); }
}

// ═══ TIMETABLE PDF (Mentor page) ═══
export async function generateTimetablePDF(data, prefs = {}) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p','mm','a4'); const logo = await loadLogo(); const title = 'Daily Timetable';
  addHeader(doc, logo, title); let y = MARGIN.top + 4;
  doc.setFont('helvetica','bold'); doc.setFontSize(24); doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Your AI-Generated Timetable', MARGIN.left, y); y += 10;
  doc.setFont('helvetica','normal'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(`Schedule for ${new Date().toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}`, MARGIN.left, y); y += 8;
  if (prefs && Object.keys(prefs).length > 0) {
    doc.setFont('helvetica','bold'); doc.setFontSize(10); doc.setTextColor(...rgb(BRAND.dark));
    doc.text('Preferences', MARGIN.left, y); y += 6;
    doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.muted));
    let cx = MARGIN.left;
    for (const [k,v] of Object.entries(prefs).filter(([,v])=>v)) {
      const t = `${k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}: ${v}`;
      const w = doc.getTextWidth(t)+8;
      if(cx+w>PAGE_W-MARGIN.right){cx=MARGIN.left;y+=8;}
      rr(doc,cx,y-4,w,7,2,BRAND.tableStripe); doc.text(t,cx+4,y); cx+=w+4;
    } y += 12;
  }
  doc.setDrawColor(...rgb(BRAND.light)); doc.setLineWidth(0.4);
  doc.line(MARGIN.left,y,PAGE_W-MARGIN.right,y); y+=8;
  const cw={time:42,subj:80,type:CONTENT_W-122};
  rr(doc,MARGIN.left,y-1,CONTENT_W,10,2,BRAND.primary);
  doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.white));
  let cx2=MARGIN.left+4; doc.text('TIME',cx2,y+5); cx2+=cw.time; doc.text('ACTIVITY',cx2,y+5); cx2+=cw.subj; doc.text('TYPE',cx2,y+5); y+=12;
  const slots = data?.daily||[];
  for(let i=0;i<slots.length;i++){
    y=newPage(doc,y,12,logo,title); const s=slots[i];
    if(i%2===0) rr(doc,MARGIN.left,y-4,CONTENT_W,10,1.5,BRAND.tableStripe);
    let x=MARGIN.left+4;
    doc.setFont('helvetica','bold'); doc.setFontSize(10); doc.setTextColor(...rgb(BRAND.dark));
    doc.text(s.time||'',x,y+1); x+=cw.time;
    doc.setFont('helvetica','normal'); doc.text((s.subject||'').substring(0,45),x,y+1); x+=cw.subj;
    const tl=(s.type||'other').toUpperCase();
    let bc=BRAND.muted; if(s.type==='study')bc=BRAND.primary; if(s.type==='college')bc=BRAND.warning; if(s.type==='break')bc=BRAND.success; if(s.type==='routine')bc=BRAND.secondary;
    const bw=doc.getTextWidth(tl)+8; rr(doc,x,y-3.5,bw,7,2,bc);
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.white)); doc.text(tl,x+4,y+1); doc.setFontSize(10); y+=11;
  }
  y+=6; y=newPage(doc,y,30,logo,title);
  doc.setDrawColor(...rgb(BRAND.light)); doc.line(MARGIN.left,y,PAGE_W-MARGIN.right,y); y+=8;
  const sc=slots.filter(s=>s.type==='study').length, bc2=slots.filter(s=>s.type==='break').length;
  doc.setFont('helvetica','bold'); doc.setFontSize(12); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Summary',MARGIN.left,y); y+=8;
  const cardW=(CONTENT_W-12)/3;
  [{l:'Total Slots',v:`${slots.length}`,c:BRAND.dark},{l:'Study Blocks',v:`${sc}`,c:BRAND.primary},{l:'Breaks',v:`${bc2}`,c:BRAND.success}].forEach((it,i)=>{
    const cx=MARGIN.left+i*(cardW+6); rr(doc,cx,y,cardW,18,3,BRAND.tableStripe);
    doc.setFont('helvetica','bold'); doc.setFontSize(16); doc.setTextColor(...it.c); doc.text(it.v,cx+cardW/2,y+9,{align:'center'});
    doc.setFont('helvetica','normal'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.muted)); doc.text(it.l,cx+cardW/2,y+15,{align:'center'});
  });
  finalize(doc); doc.save('StudyVerse_Timetable.pdf');
}

// ═══ ASSESSMENT PDF ═══
export async function generateAssessmentPDF(topic, results, totalScore, maxScore) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p','mm','a4'); const logo = await loadLogo(); const title = 'Assessment Report';
  addHeader(doc, logo, title); let y = MARGIN.top + 4;
  doc.setFont('helvetica','bold'); doc.setFontSize(24); doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Assessment Report', MARGIN.left, y); y += 10;
  doc.setFont('helvetica','normal'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(`Topic: ${topic}`, MARGIN.left, y); y+=6;
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'})}`, MARGIN.left, y); y+=10;
  const pct = Math.round((totalScore/maxScore)*100);
  let sc=BRAND.success, sl='Excellent';
  if(pct<40){sc=BRAND.danger;sl='Needs Improvement';}else if(pct<70){sc=BRAND.warning;sl='Good';}else if(pct<90){sc=BRAND.secondary;sl='Very Good';}
  rr(doc,MARGIN.left,y,CONTENT_W,30,4,BRAND.tableStripe);
  doc.setFont('helvetica','bold'); doc.setFontSize(32); doc.setTextColor(...sc); doc.text(`${totalScore}`,MARGIN.left+14,y+18);
  doc.setFontSize(14); doc.setTextColor(...rgb(BRAND.muted));
  doc.setFontSize(32); const bw=doc.getTextWidth(`${totalScore}`); doc.setFontSize(14);
  doc.text(` / ${maxScore}`,MARGIN.left+14+bw+2,y+18);
  const bx=MARGIN.left+80; rr(doc,bx,y+8,30,12,3,sc);
  doc.setFont('helvetica','bold'); doc.setFontSize(12); doc.setTextColor(...rgb(BRAND.white)); doc.text(`${pct}%`,bx+15,y+16,{align:'center'});
  doc.setFontSize(14); doc.setTextColor(...sc); doc.text(sl,bx+38,y+16);
  rr(doc,MARGIN.left+8,y+24,CONTENT_W-16,3,1.5,[220,220,230]);
  rr(doc,MARGIN.left+8,y+24,(CONTENT_W-16)*(pct/100),3,1.5,sc);
  y+=38;
  doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Detailed Results',MARGIN.left,y); y+=3;
  doc.setDrawColor(...rgb(BRAND.primary)); doc.setLineWidth(0.5); doc.line(MARGIN.left,y,MARGIN.left+40,y); y+=8;
  for(let i=0;i<results.length;i++){
    const r=results[i]; const al=wrap(doc,r.answer||'No answer',CONTENT_W-20); const fl=wrap(doc,r.feedback||'',CONTENT_W-20);
    const ch=28+(al.length*5)+(fl.length*4.5); y=newPage(doc,y,ch+6,logo,title);
    rr(doc,MARGIN.left,y,CONTENT_W,ch,3,BRAND.tableStripe);
    rr(doc,MARGIN.left+4,y+4,10,7,2,BRAND.primary);
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.white)); doc.text(`Q${i+1}`,MARGIN.left+9,y+9,{align:'center'});
    doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.dark));
    const ql=wrap(doc,r.question,CONTENT_W-30); doc.text(ql,MARGIN.left+18,y+9);
    let iy=y+9+(ql.length*5)+2;
    const qs=r.score||0; let qc=BRAND.success; if(qs<4)qc=BRAND.danger; else if(qs<7)qc=BRAND.warning;
    rr(doc,PAGE_W-MARGIN.right-24,y+3,20,8,2,qc);
    doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.white)); doc.text(`${qs}/10`,PAGE_W-MARGIN.right-14,y+8.5,{align:'center'});
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.muted)); doc.text('YOUR ANSWER',MARGIN.left+8,iy); iy+=4;
    doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.dark)); doc.text(al,MARGIN.left+8,iy); iy+=al.length*4.5+3;
    if(r.feedback){ doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.secondary)); doc.text('AI FEEDBACK',MARGIN.left+8,iy); iy+=4;
      doc.setFont('helvetica','italic'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.muted)); doc.text(fl,MARGIN.left+8,iy);
    } y+=ch+6;
  }
  finalize(doc); doc.save('StudyVerse_Assessment.pdf');
}

// ═══ DAILY TIMETABLE PDF (Home page) ═══
export async function generateDailyTimetablePDF(slots, statuses) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p','mm','a4'); const logo = await loadLogo(); const title = "Today's Timetable";
  addHeader(doc, logo, title); let y = MARGIN.top + 4;
  doc.setFont('helvetica','bold'); doc.setFontSize(22); doc.setTextColor(...rgb(BRAND.dark));
  doc.text("Today's Schedule", MARGIN.left, y); y+=8;
  doc.setFont('helvetica','normal'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(new Date().toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}), MARGIN.left, y); y+=10;
  const done = Object.values(statuses||{}).filter(s=>s==='done').length;
  const skip = Object.values(statuses||{}).filter(s=>s==='skipped').length;
  const cardW2 = (CONTENT_W-8)/3;
  [{l:'Total Slots',v:`${slots.length}`,c:BRAND.dark},{l:'Completed',v:`${done}`,c:BRAND.success},{l:'Skipped',v:`${skip}`,c:BRAND.danger}].forEach((it,i)=>{
    const cx=MARGIN.left+i*(cardW2+4); rr(doc,cx,y,cardW2,16,3,BRAND.tableStripe);
    doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.setTextColor(...it.c); doc.text(it.v,cx+cardW2/2,y+8,{align:'center'});
    doc.setFont('helvetica','normal'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.muted)); doc.text(it.l,cx+cardW2/2,y+13,{align:'center'});
  }); y+=22;
  rr(doc,MARGIN.left,y-1,CONTENT_W,10,2,BRAND.primary);
  doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.white));
  let hx=MARGIN.left+4; doc.text('TIME',hx,y+5); hx+=42; doc.text('ACTIVITY',hx,y+5); hx+=72; doc.text('TYPE',hx,y+5); hx+=30; doc.text('STATUS',hx,y+5); y+=12;
  for(let i=0;i<slots.length;i++){
    y=newPage(doc,y,11,logo,title); const s=slots[i]; const st=statuses?.[i]||'pending';
    if(i%2===0) rr(doc,MARGIN.left,y-4,CONTENT_W,10,1.5,BRAND.tableStripe);
    let x=MARGIN.left+4; doc.setFontSize(10);
    doc.setFont('helvetica','bold'); doc.setTextColor(...rgb(BRAND.dark)); doc.text(s.time||'',x,y+1); x+=42;
    doc.setFont('helvetica','normal'); doc.text((s.subject||'').substring(0,35),x,y+1); x+=72;
    const tl=(s.type||'').toUpperCase(); let bc=BRAND.muted;
    if(s.type==='study')bc=BRAND.primary; if(s.type==='college')bc=BRAND.warning; if(s.type==='break')bc=BRAND.success; if(s.type==='routine')bc=BRAND.secondary;
    const tw=doc.getTextWidth(tl)+8; rr(doc,x,y-3.5,tw,7,2,bc);
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.white)); doc.text(tl,x+4,y+1); x+=30;
    const stLabel = st==='done'?'DONE':st==='skipped'?'SKIPPED':'—';
    const stColor = st==='done'?BRAND.success:st==='skipped'?BRAND.danger:BRAND.muted;
    doc.setFontSize(8); doc.setTextColor(...stColor); doc.text(stLabel,x+4,y+1);
    doc.setFontSize(10); y+=11;
  }
  finalize(doc); doc.save('StudyVerse_DailyTimetable.pdf');
}

// ═══ DASHBOARD PDF ═══
export async function generateDashboardPDF(data) {
  const { user, stats, chartData, subjectData, warnings, suggestions, todayTasks } = data;
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p','mm','a4'); const logo = await loadLogo(); const title = 'Dashboard Report';
  addHeader(doc, logo, title); let y = MARGIN.top + 4;

  // Title
  doc.setFont('helvetica','bold'); doc.setFontSize(24); doc.setTextColor(...rgb(BRAND.dark));
  doc.text('Student Dashboard Report', MARGIN.left, y); y+=10;
  doc.setFont('helvetica','normal'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'})}`, MARGIN.left, y); y+=12;

  // Profile card
  rr(doc,MARGIN.left,y,CONTENT_W,28,4,BRAND.tableStripe);
  doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(...rgb(BRAND.primary)); doc.text('STUDENT PROFILE',MARGIN.left+8,y+6);
  doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.setTextColor(...rgb(BRAND.dark)); doc.text(user?.name||'Student',MARGIN.left+8,y+14);
  doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.muted));
  doc.text(`${user?.email||''} · ${user?.college||''} · ${user?.course||''} · ${user?.year||''}`,MARGIN.left+8,y+20);
  y+=34;

  // Stats cards
  const sCards=[{l:'Total XP',v:`${stats?.xp||0}`,c:BRAND.primary},{l:'Day Streak',v:`${stats?.streak||0}`,c:BRAND.secondary},{l:'Level',v:`${stats?.level||1}`,c:BRAND.warning},{l:'Badges',v:`${Object.keys(stats?.badges||{}).length}`,c:BRAND.success}];
  const sw=(CONTENT_W-18)/4;
  sCards.forEach((it,i)=>{
    const cx=MARGIN.left+i*(sw+6); rr(doc,cx,y,sw,20,3,BRAND.tableStripe);
    doc.setFont('helvetica','bold'); doc.setFontSize(16); doc.setTextColor(...it.c); doc.text(it.v,cx+sw/2,y+10,{align:'center'});
    doc.setFont('helvetica','normal'); doc.setFontSize(7); doc.setTextColor(...rgb(BRAND.muted)); doc.text(it.l,cx+sw/2,y+16,{align:'center'});
  }); y+=28;

  // Warnings
  if(warnings?.length>0){
    doc.setFont('helvetica','bold'); doc.setFontSize(12); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Alerts & Notifications',MARGIN.left,y); y+=7;
    for(const w of warnings){
      y=newPage(doc,y,8,logo,title);
      doc.setFont('helvetica','normal'); doc.setFontSize(9);
      doc.setTextColor(...(w.type==='warning'?BRAND.danger:BRAND.secondary));
      doc.text(`• ${w.msg}`,MARGIN.left+4,y); y+=6;
    } y+=4;
  }

  // Study Hours chart (table form)
  y=newPage(doc,y,50,logo,title);
  doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Productivity Charts',MARGIN.left,y); y+=3;
  doc.setDrawColor(...rgb(BRAND.primary)); doc.setLineWidth(0.5); doc.line(MARGIN.left,y,MARGIN.left+45,y); y+=8;

  // Study hours table
  doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Study Hours — Last 7 Days',MARGIN.left,y); y+=6;
  rr(doc,MARGIN.left,y-1,CONTENT_W,10,2,BRAND.primary);
  doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.white));
  doc.text('DAY',MARGIN.left+4,y+5); doc.text('HOURS',MARGIN.left+50,y+5); doc.text('TASKS',MARGIN.left+95,y+5); doc.text('SCORE',MARGIN.left+135,y+5); y+=12;
  for(let i=0;i<(chartData||[]).length;i++){
    const d=chartData[i]; if(i%2===0) rr(doc,MARGIN.left,y-4,CONTENT_W,9,1,BRAND.tableStripe);
    doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.dark));
    doc.text(d.day||'',MARGIN.left+4,y); doc.text(`${(d.hours||0).toFixed(1)}h`,MARGIN.left+50,y);
    doc.text(`${d.tasks||0}`,MARGIN.left+95,y); doc.text(`${d.score||0}%`,MARGIN.left+135,y); y+=9;
  } y+=6;

  // Subject progress table
  y=newPage(doc,y,40,logo,title);
  doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.dark)); doc.text('Subject Progress',MARGIN.left,y); y+=6;
  for(let i=0;i<(subjectData||[]).length;i++){
    y=newPage(doc,y,12,logo,title); const s=subjectData[i];
    doc.setFont('helvetica','normal'); doc.setFontSize(10); doc.setTextColor(...rgb(BRAND.dark));
    doc.text(s.subject||'',MARGIN.left+4,y+1);
    doc.text(`${s.progress||0}%`,MARGIN.left+CONTENT_W-20,y+1);
    rr(doc,MARGIN.left+50,y-2,CONTENT_W-80,5,2,[220,220,230]);
    const pw=Math.max(1,(CONTENT_W-80)*(s.progress||0)/100);
    const pc=s.progress>=80?BRAND.success:s.progress>=50?BRAND.primary:BRAND.danger;
    rr(doc,MARGIN.left+50,y-2,pw,5,2,pc); y+=10;
  } y+=6;

  // Today's tasks
  y=newPage(doc,y,30,logo,title);
  doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.dark)); doc.text("Today's Tasks",MARGIN.left,y); y+=6;
  if(!todayTasks||todayTasks.length===0){
    doc.setFont('helvetica','italic'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.muted)); doc.text('No tasks for today.',MARGIN.left+4,y); y+=8;
  } else {
    for(const t of todayTasks){
      y=newPage(doc,y,8,logo,title);
      doc.setFont('helvetica','normal'); doc.setFontSize(9);
      doc.setTextColor(...(t.completed?BRAND.success:BRAND.dark));
      doc.text(`${t.completed?'✓':'○'} ${t.title||''}${t.priority?' ('+t.priority+')':''}`,MARGIN.left+4,y); y+=6;
    } y+=4;
  }

  // AI Suggestions
  y=newPage(doc,y,30,logo,title);
  doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.setTextColor(...rgb(BRAND.dark)); doc.text('AI Insights & Suggestions',MARGIN.left,y); y+=6;
  for(const s of (suggestions||[])){
    y=newPage(doc,y,14,logo,title);
    rr(doc,MARGIN.left,y-2,CONTENT_W,12,2,BRAND.tableStripe);
    doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(...rgb(BRAND.dark));
    const lines = wrap(doc, typeof s==='string'?s:(s.suggestion||s.p||s.text||JSON.stringify(s)), CONTENT_W-12);
    doc.text(lines[0]||'',MARGIN.left+6,y+4); y+=14;
  }

  finalize(doc); doc.save('StudyVerse_Dashboard_Report.pdf');
}
